# Generated by Django 4.1.7 on 2023-04-04 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, null=True, unique=True)),
                ('username', models.CharField(default='default_name', max_length=100)),
                ('last_name', models.CharField(default='default_last_name', max_length=100)),
                ('email', models.EmailField(default='defaultEmail@kursa4.com', max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('beginner_friendly', models.BooleanField(default=False)),
                ('crossfit', models.BooleanField(default=False)),
                ('general_workout', models.BooleanField(default=False)),
                ('cardio', models.BooleanField(default=False)),
                ('back', models.BooleanField(default=False)),
                ('legs', models.BooleanField(default=False)),
                ('chest', models.BooleanField(default=False)),
                ('shoulders', models.BooleanField(default=False)),
                ('biceps', models.BooleanField(default=False)),
                ('triceps', models.BooleanField(default=False)),
                ('abs', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('is_competition', models.BooleanField(default=False)),
                ('is_exercise', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'activities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('post_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'trainer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(default=2001, null=True)),
                ('month', models.IntegerField(default=1, null=True)),
                ('day', models.CharField(default=1, max_length=100, null=True)),
                ('length', models.CharField(default=1, max_length=100, null=True)),
                ('personal_highscores_amount', models.CharField(default=0, max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workouts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('people_limit', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pract.activities')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pract.trainer')),
            ],
            options={
                'db_table': 'schedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(default=0, max_length=100, null=True)),
                ('reps', models.CharField(default=0, max_length=100, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='pract.activities')),
                ('workout_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='pract.workouts')),
            ],
            options={
                'db_table': 'exercises',
                'managed': True,
            },
        ),
    ]
