# Generated by Django 4.1.7 on 2023-03-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('beginner_friendly', models.BooleanField(default=False, null=True)),
                ('crossfit', models.BooleanField(default=False, null=True)),
                ('general_workout', models.BooleanField(default=False, null=True)),
                ('cardio', models.BooleanField(default=False, null=True)),
                ('legs', models.BooleanField(default=False, null=True)),
                ('chest', models.BooleanField(default=False, null=True)),
                ('shoulders', models.BooleanField(default=False, null=True)),
                ('biceps', models.BooleanField(default=False, null=True)),
                ('triceps', models.BooleanField(default=False, null=True)),
                ('is_group', models.BooleanField(default=False, null=True)),
                ('is_competition', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'activities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'trainer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('length', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_hightscores_amount', models.IntegerField(default=0, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('people_limit', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pract.activities')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pract.trainer')),
            ],
            options={
                'db_table': 'schedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.IntegerField(default=0, null=True)),
                ('reps', models.IntegerField(default=0, null=True)),
                ('workout_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='pract.workouts')),
            ],
            options={
                'db_table': 'exercises',
                'managed': True,
            },
        ),
    ]
