# Generated by Django 4.1.7 on 2023-04-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='user',
        ),
    ]
