# Generated by Django 4.1.7 on 2023-04-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0003_workouts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='workout_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='pract.workouts'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pract.activities'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pract.trainer'),
        ),
    ]
