# Generated by Django 4.1.7 on 2023-03-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0003_alter_exercises_workout_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workouts',
            table='workouts',
        ),
    ]
