# Generated by Django 4.1.7 on 2023-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0003_remove_schedule_name_schedule_is_free_schedule_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='people_enlisted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='people_limit',
            field=models.IntegerField(default=20),
        ),
    ]
