# Generated by Django 4.1.7 on 2023-04-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0004_alter_exercises_workout_id_alter_schedule_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='abs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='back',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='beginner_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='biceps',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='chest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='crossfit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='general_workout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='is_competition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='is_exercise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='legs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='shoulders',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='triceps',
            field=models.BooleanField(default=False),
        ),
    ]
