# Generated by Django 4.1.7 on 2023-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0004_alter_workouts_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='date',
        ),
        migrations.AddField(
            model_name='workouts',
            name='day',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='month',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='year',
            field=models.IntegerField(default=2001, null=True),
        ),
    ]
