# Generated by Django 4.1.7 on 2023-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0005_alter_exercises_workout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
