# Generated by Django 4.1.7 on 2023-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0005_activities_abs_alter_activities_back_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='name',
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(default='defaultEmail@kursa4.com', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='clients',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='clients',
            name='login',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='username',
            field=models.CharField(default='default_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(default='default_last_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
