# Generated by Django 4.1.7 on 2023-03-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0005_remove_workouts_date_workouts_day_workouts_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='length',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
