# Generated by Django 4.1.7 on 2023-03-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0006_alter_workouts_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouts',
            old_name='personal_hightscores_amount',
            new_name='personal_highscores_amount',
        ),
    ]
