# Generated by Django 4.1.7 on 2023-04-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0006_workouts_endtime_workouts_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='endTime',
            field=models.TimeField(default='1:00:00'),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='startTime',
            field=models.TimeField(default='0:00:00'),
        ),
    ]
