# Generated by Django 4.1.7 on 2023-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0007_alter_workouts_endtime_alter_workouts_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_free',
        ),
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
