# Generated by Django 4.1.7 on 2023-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0007_rename_personal_hightscores_amount_workouts_personal_highscores_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='reps',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='weight',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='day',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='length',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='month',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='personal_highscores_amount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='year',
            field=models.CharField(default=2001, max_length=100, null=True),
        ),
    ]
