# Generated by Django 4.1.7 on 2023-03-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0008_alter_exercises_reps_alter_exercises_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='month',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='year',
            field=models.IntegerField(default=2001, null=True),
        ),
    ]
