# Generated by Django 4.1.7 on 2023-03-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0009_alter_workouts_month_alter_workouts_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
