# Generated by Django 4.1.7 on 2023-04-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0010_alter_schedule_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='timeFinish',
            new_name='finishTime',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='timeStart',
            new_name='startTime',
        ),
    ]
