# Generated by Django 4.1.7 on 2023-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0010_news_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='post_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
