# Generated by Django 4.1.7 on 2023-04-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0011_rename_timefinish_schedule_finishtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='finishTime',
            new_name='endTime',
        ),
    ]
