# Generated by Django 4.1.7 on 2023-04-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0014_appointments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date',
        ),
    ]
